apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: fa20fb24445a3f6ca2ebc3386afcc020caa33911
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: fa20fb24445a3f6ca2ebc3386afcc020caa33911
resources:
  - manifests.yaml