apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: ac0dfde75cae11824be5fd35dfb56968d3d050c3
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: ac0dfde75cae11824be5fd35dfb56968d3d050c3
resources:
  - manifests.yaml