apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: 9c05f788993a224c2d0fbae564b62783b4f570cf
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: 9c05f788993a224c2d0fbae564b62783b4f570cf
resources:
  - manifests.yaml