apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: 72a9baf0c4ee6fb086faa915e226d374271ea76b
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: 72a9baf0c4ee6fb086faa915e226d374271ea76b
resources:
  - manifests.yaml