apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevops.azurecr.io/azvote/azure-vote-front
    newTag: fb0856a4e357abe29a41079d2250bd690ed50252
  - name: fsdetdevops.azurecr.io/azvote/azure-vote-back
    newTag: fb0856a4e357abe29a41079d2250bd690ed50252
resources:
  - manifests.yaml