apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: fc2d64f226595a740a176019eb44e218b3f72b50
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: fc2d64f226595a740a176019eb44e218b3f72b50
resources:
  - manifests.yaml