apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: 2fc44426985da26aaed219fdbdfb7cc47bff9892
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: 2fc44426985da26aaed219fdbdfb7cc47bff9892
resources:
  - manifests.yaml