apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: 934e89124a0387908d4833668fb8ad2acdf71035
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: 934e89124a0387908d4833668fb8ad2acdf71035
resources:
  - manifests.yaml