apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: fd386bd3458a813971028f5ed0a0754ca44fbc72
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: fd386bd3458a813971028f5ed0a0754ca44fbc72
resources:
  - manifests.yaml