apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: c01a262ed8d57fd087517060042c2428a95f4716
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: c01a262ed8d57fd087517060042c2428a95f4716
resources:
  - manifests.yaml