apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: 25466e81e162caf650fd62e4f3228d22e2c259d1
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: 25466e81e162caf650fd62e4f3228d22e2c259d1
resources:
  - manifests.yaml