apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

images:
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-front
    newTag: ea7a4b6fcaec1887d4d2e0d0142120a2d89e8ee8
  - name: fsdetdevopssandbox.azurecr.io/azvote/azure-vote-back
    newTag: ea7a4b6fcaec1887d4d2e0d0142120a2d89e8ee8
resources:
  - manifests.yaml